{
  "hash": "a39e8b0e5891728210cea330165d9467",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Case Study 1\"\nauthor: \"Sneha Manu Jacob\"\ndate: \"2024-10-11\"\ncategories: [A2, movie_profit]\n---\n\n\n\n## Introduction\n\nThis is a dataset pertaining to movies and genres, modified for ease of analysis and plotting.\n\n## Playing with and understanding the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(skimr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\n```\n:::\n\n\n\n### Acquiring the data:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_profit <- read_delim(\"../../data/movie_profit.csv\", delim=\";\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 3310 Columns: 10\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \";\"\nchr  (4): movie, distributor, mpaa_rating, genre\ndbl  (4): production_budget, domestic_gross, worldwide_gross, decade\nnum  (1): profit_ratio\ndate (1): release_date\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nmovie_profit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,310 × 10\n   release_date movie           production_budget domestic_gross worldwide_gross\n   <date>       <chr>                       <dbl>          <dbl>           <dbl>\n 1 2005-07-22   November                   250000         191862          191862\n 2 1998-08-28   I Married a St…            250000         203134          203134\n 3 1997-03-28   Love and Other…            250000         212285          743216\n 4 2000-07-14   Chuck&Buck                 250000        1055671         1157672\n 5 2011-10-28   Like Crazy                 250000        3395391         3728400\n 6 2003-04-11   Better Luck To…            250000        3802390         3809226\n 7 2017-04-28   Sleight                    250000        3930990         3934450\n 8 2002-06-28   Lovely and Ama…            250000        4210379         4613482\n 9 2012-08-17   Compliance                 270000         319285          830700\n10 2005-05-06   Fighting Tommy…            300000          10514           10514\n# ℹ 3,300 more rows\n# ℹ 5 more variables: distributor <chr>, mpaa_rating <chr>, genre <chr>,\n#   profit_ratio <dbl>, decade <dbl>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(movie_profit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,310\nColumns: 10\n$ release_date      <date> 2005-07-22, 1998-08-28, 1997-03-28, 2000-07-14, 201…\n$ movie             <chr> \"November\", \"I Married a Strange Person\", \"Love and …\n$ production_budget <dbl> 250000, 250000, 250000, 250000, 250000, 250000, 2500…\n$ domestic_gross    <dbl> 191862, 203134, 212285, 1055671, 3395391, 3802390, 3…\n$ worldwide_gross   <dbl> 191862, 203134, 743216, 1157672, 3728400, 3809226, 3…\n$ distributor       <chr> \"Other\", \"Other\", \"Other\", \"Other\", \"Paramount Pictu…\n$ mpaa_rating       <chr> \"R\", NA, \"R\", \"R\", \"PG-13\", \"R\", \"R\", \"R\", \"R\", \"R\",…\n$ genre             <chr> \"Drama\", \"Comedy\", \"Comedy\", \"Drama\", \"Drama\", \"Dram…\n$ profit_ratio      <dbl> 7.674480e+13, 8.125360e+13, 2.972864e+14, 4.630688e+…\n$ decade            <dbl> 2000, 1990, 1990, 2000, 2010, 2000, 2010, 2000, 2010…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(movie_profit)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |             |\n|:------------------------|:------------|\n|Name                     |movie_profit |\n|Number of rows           |3310         |\n|Number of columns        |10           |\n|_______________________  |             |\n|Column type frequency:   |             |\n|character                |4            |\n|Date                     |1            |\n|numeric                  |5            |\n|________________________ |             |\n|Group variables          |None         |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|movie         |         0|          1.00|   1|  35|     0|     3310|          0|\n|distributor   |        42|          0.99|   5|  18|     0|        6|          0|\n|mpaa_rating   |       130|          0.96|   1|   5|     0|        4|          0|\n|genre         |         0|          1.00|   5|   9|     0|        5|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|release_date  |         0|             1|1936-02-05 |2017-12-22 |2005-06-30 |     1723|\n\n\n**Variable type: numeric**\n\n|skim_variable     | n_missing| complete_rate|         mean|           sd|       p0|          p25|          p50|          p75|         p100|hist  |\n|:-----------------|---------:|-------------:|------------:|------------:|--------:|------------:|------------:|------------:|------------:|:-----|\n|production_budget |         0|             1| 3.326794e+07| 3.460741e+07| 2.50e+05| 9.500000e+06| 2.000000e+07| 4.500000e+07| 1.750000e+08|▇▂▁▁▁ |\n|domestic_gross    |         0|             1| 4.551509e+07| 5.852794e+07| 0.00e+00| 6.530094e+06| 2.558731e+07| 6.046695e+07| 4.745447e+08|▇▁▁▁▁ |\n|worldwide_gross   |         0|             1| 9.384123e+07| 1.389514e+08| 4.23e+02| 1.086144e+07| 4.040903e+07| 1.184703e+08| 1.162782e+09|▇▁▁▁▁ |\n|profit_ratio      |         0|             1| 4.319388e+14| 1.501736e+15| 1.38e+10| 7.861269e+13| 1.962499e+14| 3.942158e+14| 4.315179e+16|▇▁▁▁▁ |\n|decade            |         0|             1| 1.998790e+03| 1.061000e+01| 1.93e+03| 1.990000e+03| 2.000000e+03| 2.010000e+03| 2.010000e+03|▁▁▁▃▇ |\n\n\n:::\n:::\n\n\n\n### Data Dictionary:\n\n| Variable name | Description | Type of variable |\n|------------------------|------------------------|------------------------|\n| movie | The title of the movie | Qualitative |\n| distributor | The company responsible for distributing the movie (e.g., Warner Bros., Disney) | Qualitative |\n| mpaa_rating | The movie's MPAA rating (e.g., G, PG, PG-13, R), which indicates the age-appropriateness of the content. | Qualitative |\n| genre | The type or category of the movie (e.g., Action, Comedy, Drama) | Qualitative |\n| release_date | The date when the movie was first released in theaters | Qualitative |\n| production_budget | The amount of money spent on producing the movie | Quantitative |\n| domestic_gross | The total earnings of the movie from domestic (usually U.S.) markets | Quantitative |\n| worldwide_gross | The total earnings of the movie from all markets worldwide | Quantitative |\n| profit_ratio | The ratio of profit earned relative to the production budget | Quantitative |\n| decade | The decade during which the movie was released | Qualitative |\n\n#### Observations:\n\n1.  The variables **mpaa_rating**, **genre**, and **distributor** are qualitative (categorical) data with a low enough number of unique levels that they could be treated as factors.\n2.  **Decade** is quantitative data but could also be treated as a factor.\n3.  There are missing values in the dataset for **mpaa_rating** and **distributor**.\n\n### Transforming the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_modified <- movie_profit %>%\n  dplyr::mutate(\n    mpaa_rating = as_factor(mpaa_rating),\n    genre = as_factor(genre),\n    distributor = as_factor(distributor),\n    decade = as_factor(decade)\n  )\nmovie_modified\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,310 × 10\n   release_date movie           production_budget domestic_gross worldwide_gross\n   <date>       <chr>                       <dbl>          <dbl>           <dbl>\n 1 2005-07-22   November                   250000         191862          191862\n 2 1998-08-28   I Married a St…            250000         203134          203134\n 3 1997-03-28   Love and Other…            250000         212285          743216\n 4 2000-07-14   Chuck&Buck                 250000        1055671         1157672\n 5 2011-10-28   Like Crazy                 250000        3395391         3728400\n 6 2003-04-11   Better Luck To…            250000        3802390         3809226\n 7 2017-04-28   Sleight                    250000        3930990         3934450\n 8 2002-06-28   Lovely and Ama…            250000        4210379         4613482\n 9 2012-08-17   Compliance                 270000         319285          830700\n10 2005-05-06   Fighting Tommy…            300000          10514           10514\n# ℹ 3,300 more rows\n# ℹ 5 more variables: distributor <fct>, mpaa_rating <fct>, genre <fct>,\n#   profit_ratio <dbl>, decade <fct>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(movie_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,310\nColumns: 10\n$ release_date      <date> 2005-07-22, 1998-08-28, 1997-03-28, 2000-07-14, 201…\n$ movie             <chr> \"November\", \"I Married a Strange Person\", \"Love and …\n$ production_budget <dbl> 250000, 250000, 250000, 250000, 250000, 250000, 2500…\n$ domestic_gross    <dbl> 191862, 203134, 212285, 1055671, 3395391, 3802390, 3…\n$ worldwide_gross   <dbl> 191862, 203134, 743216, 1157672, 3728400, 3809226, 3…\n$ distributor       <fct> Other, Other, Other, Other, Paramount Pictures, Para…\n$ mpaa_rating       <fct> R, NA, R, R, PG-13, R, R, R, R, R, R, R, PG-13, NA, …\n$ genre             <fct> Drama, Comedy, Comedy, Drama, Drama, Drama, Action, …\n$ profit_ratio      <dbl> 7.674480e+13, 8.125360e+13, 2.972864e+14, 4.630688e+…\n$ decade            <fct> 2000, 1990, 1990, 2000, 2010, 2000, 2010, 2000, 2010…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(movie_modified)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |               |\n|:------------------------|:--------------|\n|Name                     |movie_modified |\n|Number of rows           |3310           |\n|Number of columns        |10             |\n|_______________________  |               |\n|Column type frequency:   |               |\n|character                |1              |\n|Date                     |1              |\n|factor                   |4              |\n|numeric                  |4              |\n|________________________ |               |\n|Group variables          |None           |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|movie         |         0|             1|   1|  35|     0|     3310|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|release_date  |         0|             1|1936-02-05 |2017-12-22 |2005-06-30 |     1723|\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                              |\n|:-------------|---------:|-------------:|:-------|--------:|:---------------------------------------|\n|distributor   |        42|          0.99|FALSE   |        6|Oth: 1737, War: 360, Son: 332, Uni: 299 |\n|mpaa_rating   |       130|          0.96|FALSE   |        4|R: 1477, PG-: 1066, PG: 552, G: 85      |\n|genre         |         0|          1.00|FALSE   |        5|Dra: 1209, Com: 798, Act: 547, Adv: 467 |\n|decade        |         0|          1.00|FALSE   |        9|200: 1387, 201: 994, 199: 607, 198: 228 |\n\n\n**Variable type: numeric**\n\n|skim_variable     | n_missing| complete_rate|         mean|           sd|       p0|          p25|          p50|          p75|         p100|hist  |\n|:-----------------|---------:|-------------:|------------:|------------:|--------:|------------:|------------:|------------:|------------:|:-----|\n|production_budget |         0|             1| 3.326794e+07| 3.460741e+07| 2.50e+05| 9.500000e+06| 2.000000e+07| 4.500000e+07| 1.750000e+08|▇▂▁▁▁ |\n|domestic_gross    |         0|             1| 4.551509e+07| 5.852794e+07| 0.00e+00| 6.530094e+06| 2.558731e+07| 6.046695e+07| 4.745447e+08|▇▁▁▁▁ |\n|worldwide_gross   |         0|             1| 9.384123e+07| 1.389514e+08| 4.23e+02| 1.086144e+07| 4.040903e+07| 1.184703e+08| 1.162782e+09|▇▁▁▁▁ |\n|profit_ratio      |         0|             1| 4.319388e+14| 1.501736e+15| 1.38e+10| 7.861269e+13| 1.962499e+14| 3.942158e+14| 4.315179e+16|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\n\n### Target and Predictor Variables:\n\nIn the context of your movie_profit data-set, a potential target variable could be **profit_ratio** (the name of the data-set does suggest so anyway). Leaving the rest of the variables- distributor, mpaa_rating, genre, decade, release_date, production_budget, domestic_gross and worldwide_gross to be predictor variables.\n\n## Defining the Research Experiment:\n\nTo analyze factors that might influence the profitability of movies. Using statistical techniques, researchers might examine the relationships between the predictor variables and the target variable (profit ratio) to determine what factors contribute to higher profitability in films.\n\nUse: The study’s findings could inform studios, distributors, and investors about what factors are most likely to lead to a movie being profitable, potentially influencing future decisions in movie production.\n\n### Analyzing the Predictor Variables:\n\n#### Distributors:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_modified %>% count(distributor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n  distributor            n\n  <fct>              <int>\n1 Other               1737\n2 Paramount Pictures   261\n3 Universal            299\n4 20th Century Fox     279\n5 Sony Pictures        332\n6 Warner Bros.         360\n7 <NA>                  42\n```\n\n\n:::\n:::\n\n\n\n##### Observations:\n\n1.  \"Other\" Distributors: Largest group with 1,737 entries, suggesting many smaller or less-known distributors.\n2.  Top Distributors include Warner Bros. (360), Sony Pictures (332), Universal (299), 20th Century Fox (279), and Paramount Pictures (261).\n\n#### Mpaa Rating:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_modified %>% count(mpaa_rating)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  mpaa_rating     n\n  <fct>       <int>\n1 R            1477\n2 PG-13        1066\n3 PG            552\n4 G              85\n5 <NA>          130\n```\n\n\n:::\n:::\n\n\n\n##### Observations:\n\nThis indicates a higher prevalence of R-rated and PG-13 movies in the data-set, with fewer G-rated films.\n\n#### Genre:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_modified %>% count(genre)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  genre         n\n  <fct>     <int>\n1 Drama      1209\n2 Comedy      798\n3 Action      547\n4 Horror      289\n5 Adventure   467\n```\n\n\n:::\n:::\n\n\n\n##### Observations:\n\nThis distribution shows a preference for Drama and Comedy in the dataset, while Horror appears less often.\n\n#### Decade:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_modified %>% count(decade)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 2\n  decade     n\n  <fct>  <int>\n1 1930       2\n2 1940       4\n3 1950       6\n4 1960      19\n5 1970      63\n6 1980     228\n7 1990     607\n8 2000    1387\n9 2010     994\n```\n\n\n:::\n:::\n\n\n\n##### Observations:\n\nThe distribution indicates a clear trend of increasing movie releases from the 1930s to the 2000s, with a noticeable decline in earlier decades.\n\n#### Production Budget:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_modified %>%\n  gf_histogram(~production_budget)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n#### Domestic Gross:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_modified %>%\n  gf_histogram(~domestic_gross)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n#### Worldwide Gross:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_modified %>%\n  gf_histogram(~worldwide_gross)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n##### Observations:\n\nThe histograms of all the quantitative predictor variables are similarly skewed to the right. A rightward skew indicates that a majority of the data points are concentrated on the lower end of the scale, with fewer high values. This could suggest that most movies in my data-set have lower production budgets or grosses, while only a few have significantly higher values.The uniform skewness across multiple variables suggests a consistent pattern in the data-set, which can indicate underlying trends or characteristics shared among the movies\n\n## Define the Question:\n\nGraph:\n\n![](images/clipboard-1930049740.png)\n\nIdentifying the type of plot: A bar plot where a quantitative variable is plotted rather than a qualitative one.\n\nQuestions:\n\n1.  How do the distributor and genre affect a movie's profitability?\n2.  Which genre is most likely to being the most profit for a distributor.\n3.  If i have a horror movie i want to bring to the theaters, which distributor would be my best bet?\n\n### Graph Replication:\n\nI examined the variables plotted- We are plotting a quantitative variable against 2 qualitative variables. Has the profit ratio been transformed in any way to be used as a bar graph- one where the count of qualitative variables are plotted? A histogram is used to plot continuous quantitative data that could be faceted by groups that are defined by levels of a qualitative data. But is it possible to plot it against 2 qulaitative variables? No, You cannot meaningfully divide categories into bins, which is the core concept behind a histogram.\n\nMaybe i could use groups to understand this data? The x axis of the graph does say median profit ratio. Using box-plots, i do find the different medians.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_modified_again <- movie_modified %>%\n  dplyr::mutate(\n    genre = factor(genre,\n      levels = c(\"Action\", \"Adventure\", \"Comedy\", \"Drama\", \"Horror\" ),\n      labels = c(\"Action\", \"Adventure\", \"Comedy\", \"Drama\", \"Horror\"),\n      ordered = TRUE\n    )\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_modified_again %>%\n  drop_na() %>%\n  gf_boxplot(reorder(genre, profit_ratio) ~ profit_ratio,\n    fill = ~genre,\n    alpha = 0.5\n  ) %>%\n  gf_facet_wrap(vars(distributor)) %>%\n  gf_refine(scale_fill_brewer(palette = \"Dark2\")) %>%\n  gf_labs(\n    title = \"Profits made by film distributors\",\n    subtitle = \"Ratio of profits to budgets\",\n    x = \"Median profit ratio\",\n    y = \"genre\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_modified_again %>%\n  drop_na() %>%\n  gf_boxplot(reorder(genre, profit_ratio) ~ log10(profit_ratio),\n    fill = ~genre,\n    alpha = 0.5\n  ) %>%\n  gf_facet_wrap(vars(distributor)) %>%\n  gf_refine(scale_fill_brewer(palette = \"Dark2\")) %>%\n  gf_labs(\n    title = \"Profits made by film distributors\",\n    subtitle = \"Ratio of profits to budgets\",\n    x = \"Median profit ratio\",\n    y = \"genre\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\nAlthough bar graphs are commonly used to represent the count or frequency of qualitative (categorical) data. They can also be used to represent quantitative data if you summarize the data in some way (e.g., using means, sums, or other aggregates).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(movie_modified_again, aes(x = genre, y = profit_ratio)) +\n  facet_wrap(vars(distributor))+\n  stat_summary(fun = \"median\", geom = \"bar\") +\n  labs(title = \"Profits made by film distributors\", subtitle = \"Ratio of profits to budgets\", x = \"Genre\", y = \"Median Profit Ratio\")+  \n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\nI tried doing this with ggformula using stat = \"summary\" and fun = \"median\" but it didn't work for some reason to i tried it out with ggplot2 and it did work.\n\nI know that I am only required to make this graph, but I'm curious about how to graph would look if i plot the mean instead of the median. Would it be easier to pull out inferences from the mean plot?\n\nfacet_wrap is used to obtain separate plots for each distributor.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(movie_modified_again, aes(x = genre, y = profit_ratio)) +\n  facet_wrap(vars(distributor))+\n  stat_summary(fun = \"mean\", geom = \"bar\") +\n  labs(title = \"Profits made by film distributors\", subtitle = \"Ratio of profits to budgets\", x = \"Genre\", y = \"Mean Profit Ratio\")+  \n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\nSo after a little bit of research, I realise, **mean** is more sensitive to **outliers** and extreme values, so it works well when the data is **normally distributed** and without significant skewness while **Median** is more **robust** in the presence of **skewed data** or **outliers** because it represents the middle value.\n\nWhen i observe the box plot, there are couple of outliers present of both sides making the data skewed, in which case, it could mislead the interpretation.Therefore, the median often provides a better sense of the \"typical\" value, making it easier to draw meaningful inferences.\n\n### Inferences:\n\n1.  Paramount pictures, Warner Bros and Sony Pictures seem to most likely gain the highest profits through horror movies.\n2.  Almost all distributors seem to make the lest amount of profits through drama movies (it's a close second otherwise). This is interesting because if we looks at the count of all genres in the data-set, drama is the most. Is this a peculiarity of the data-set? If not, if it is most likely to bring in the least profit, why do they make it so much?\n\nThis makes me curious about the count of genre by distributors.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~ genre | distributor, fill = ~genre, data = movie_modified) %>%\n  gf_labs(title = \"Counts of genre by distributors\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n3.  This is interesting because even though Paramount pictures, Warner Bros and Sony Pictures are most likely to gain highest profits through horror movies, these movies are of the least count in their data-set.\n4.  For Universal Studio and 20th Century Fox, adventure is the genre that's most likely to bring in a high profit. Supporting this, 20th Century Fox does have a high count of adventure films, but Universal studio that has a higher median profit ratio for Adventure even compared to 20th Century fox, has a very low count (the second lowest they have) when it comes to adventure movies.\n5.  While comedy brings in a good profit ratio for Universal Studio and and 20th Century Fox, not so much for any of the other distributors. What might that be about? The count of comedy films seem to be similar for all distributors despite this.\n6.  If I were to invest in movie production ventures, which are the two best genres that you might decide to invest in? It would be either horror or adventure. I'm most likely to gain profits with these 2 options.\n\n## My Story:\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}